// lib/export.ts
import { ImprintReport, Author } from '@/types';
import { format } from 'date-fns';

export function reportToMarkdown(report: ImprintReport, author: Author): string {
  const date = format(new Date(report.generatedAt), 'MMMM d, yyyy');
  const lines: string[] = [];

  lines.push(`# Cognitive Imprint: ${author.name}`);
  lines.push(`**Generated:** ${date}  `);
  lines.push(`**Corpus:** ${report.documentCount} documents · ${report.totalWordCount.toLocaleString()} words  `);
  lines.push(`**Date range:** ${report.dateRange.start} → ${report.dateRange.end}  `);
  lines.push(`**Confidence:** ${report.confidence} — ${report.confidenceNote}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  lines.push('## Imprint Summary');
  lines.push('');
  lines.push(`> ${report.imprintSummary}`);
  lines.push('');

  lines.push('## Scores');
  lines.push('');
  const scores = report.scores;
  const scoreEntries = [
    ['Compression Strength', scores.compressionStrength],
    ['Argument Completeness', scores.argumentCompleteness],
    ['Framework Stability', scores.frameworkStability],
    ['Extrapolation Risk', scores.extrapolationRisk],
  ] as const;

  for (const [label, s] of scoreEntries) {
    lines.push(`### ${label}: ${s.score}/10`);
    lines.push(s.explanation);
    if (s.evidence?.length) {
      for (const e of s.evidence) {
        lines.push(`> "${e}"`);
      }
    }
    lines.push('');
  }

  lines.push('## Recurring Themes');
  lines.push('');
  for (const t of report.recurringThemes) {
    lines.push(`- ${t}`);
  }
  lines.push('');

  lines.push('## Cognitive Habits');
  lines.push('');
  for (const h of report.cognitiveHabits) {
    lines.push(`### ${h.habit} *(${h.frequency})*`);
    if (h.evidence?.length) {
      for (const e of h.evidence) {
        lines.push(`> "${e}"`);
      }
    }
    lines.push('');
  }

  lines.push('## Reasoning Patterns');
  lines.push('');
  for (const r of report.reasoningPatterns) {
    lines.push(`### ${r.pattern}`);
    lines.push(`**Shape:** ${r.shape}`);
    if (r.evidence?.length) {
      for (const e of r.evidence) {
        lines.push(`> "${e}"`);
      }
    }
    lines.push('');
  }

  lines.push('## Argument Gap Patterns');
  lines.push('');
  for (const g of report.argumentGapPatterns) {
    lines.push(`### ${g.gap} *(${g.severity})*`);
    if (g.evidence?.length) {
      for (const e of g.evidence) {
        lines.push(`> "${e}"`);
      }
    }
    lines.push('');
  }

  lines.push('## Strengths');
  lines.push('');
  for (const s of report.strengths) {
    lines.push(`### ${s.strength}`);
    if (s.evidence?.length) {
      for (const e of s.evidence) {
        lines.push(`> "${e}"`);
      }
    }
    lines.push('');
  }

  lines.push('## Risk Signals');
  lines.push('');
  for (const r of report.riskSignals) {
    lines.push(`### ${r.signal}`);
    if (r.evidence?.length) {
      for (const e of r.evidence) {
        lines.push(`> "${e}"`);
      }
    }
    lines.push('');
  }

  lines.push('## Style Markers');
  lines.push('');
  for (const m of report.styleMarkers) {
    lines.push(`- ${m}`);
  }
  lines.push('');

  lines.push('---');
  lines.push('*Generated by Cognitive Imprint*');

  return lines.join('\n');
}
